### ISSUE TITLE
Repetitive API Call

### ISSUE THREAD

**Issue by mithraan17** [wenwei1234/weather-app#3]
https://github.com/wenwei1234/weather-app/blob/1543a462901779e4988d0811b47e7f7ed3bf1f12/src/App.js#L16-L29

You are making two API requests within the fetchWeather function. Both requests share the same URL structure except for the endpoint (weather vs forecast). Instead of repeating the axios calls, you can create a helper function to handle the fetching logic, which will make your code more maintainable and reusable.

**Comment by wenwei1234** [comment]
Resolved by implementing the solution above.
