### ISSUE TITLE
Better to have different components instead of a single file

### ISSUE THREAD

**Issue by Moesha1905** [wenwei1234/weather-app#7]
https://github.com/wenwei1234/weather-app/blob/1543a462901779e4988d0811b47e7f7ed3bf1f12/src/App.js#L5

One of React's features is the component-focused architecture so utilising it would be efficient
It would be better to split the components in the existing file into different files and integrate it together
It would make it more readable and accessible for specific codes easily

**Comment by wenwei1234** [comment]
Resolved
