### ISSUE TITLE
State update dependency in changeUnit function

### ISSUE THREAD

**Issue by Moesha1905** [wenwei1234/weather-app#8]
https://github.com/wenwei1234/weather-app/blob/1543a462901779e4988d0811b47e7f7ed3bf1f12/src/App.js#L38-L41

Avoid updating state after setUnit without guaranteeing fresh data
The setUnit is asynchronous some times and could cause unnecessary requests

Solution:
Try passing the city explicitly or make use of the useEffect function

**Comment by wenwei1234** [comment]
Resolved
